import 'package:puzzle_engine/puzzle_engine.dart';

/// One Duo puzzle whose measured tier is pinned down in source.
class DuoCorpusEntry {
  const DuoCorpusEntry({
    required this.seed,
    required this.difficulty,
    required this.hardest,
    required this.deductions,
    required this.givens,
    required this.badges,
  });

  /// The grid shape. Only the 6x6 today.
  DuoSpec get spec => DuoSpec.standard;

  /// The seed handed to `generateAt`.
  final int seed;

  /// The tier that was asked for, and measured back.
  final PuzzleDifficulty difficulty;

  /// The hardest rung of the ladder the technique solver needed.
  final DuoTechnique hardest;

  /// How many deductions the whole solve took.
  final int deductions;

  /// The givens, one character per cell, row-major: `.` empty, `o` circle,
  /// `s` square.
  final String givens;

  /// The badges, `a:b:r` each with `r` an `=` or an `x`, comma-separated.
  final String badges;

  /// [givens] as the engine wants it.
  List<DuoSymbol?> get givenList => <DuoSymbol?>[
    for (final String cell in givens.split(''))
      switch (cell) {
        'o' => DuoSymbol.circle,
        's' => DuoSymbol.square,
        _ => null,
      },
  ];

  /// [badges] as the engine wants it.
  List<DuoBadge> get badgeList => <DuoBadge>[
    if (badges.isNotEmpty)
      for (final String badge in badges.split(','))
        DuoBadge(
          a: int.parse(badge.split(':')[0]),
          b: int.parse(badge.split(':')[1]),
          relation: badge.split(':')[2] == '='
              ? DuoRelation.equal
              : DuoRelation.unequal,
        ),
  ];
}

/// Duo puzzles with their tiers recorded, so retuning shows up as a diff.
///
/// Difficulty is not an absolute: the boundaries in [DuoBoundaries] and the
/// carving bias in the generator are expected to move as real puzzles
/// accumulate. What must never happen is for them to move *quietly*. Every entry
/// here is regenerated by the same call the app makes, so a change to the
/// ladder, the rater or the generator turns into a visible edit to this file
/// that has to be looked at and accepted, rather than a silent shift in what
/// "Medium" means to a player.
///
/// To regenerate: run the corpus test, read the mismatch it prints, and update
/// the entry — never adjust the assertion to fit.
const List<DuoCorpusEntry> duoDifficultyCorpus = <DuoCorpusEntry>[
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.lineFull,
    deductions: 11,
    givens: 's..s.oo.so.soos.o.s.oso.osoossso..so',
    badges: '0:6:x,2:8:x,6:7:=,9:15:x,10:11:=,15:16:x,15:21:=,18:19:=,20:26:=,22:23:=,23:29:x,26:27:=,26:32:x,29:35:x,32:33:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.lineFull,
    deductions: 11,
    givens: '...osss.ososssoosoos.oos..sso.o.os..',
    badges: '2:8:x,3:4:x,4:10:x,8:14:=,9:10:x,11:17:x,12:13:=,15:16:x,16:22:x,18:24:x,20:21:x,22:23:x,23:29:x,24:25:x,30:31:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.lineFull,
    deductions: 11,
    givens: '.s.s..sos.ooo.s..so.ossososooso.o.ss',
    badges: '0:1:=,1:2:x,1:7:x,3:9:=,7:8:x,8:14:=,11:17:x,13:14:x,16:17:=,19:20:x,22:23:x,22:28:x,23:29:x,24:25:x,25:31:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 20,
    givens: '.s..oo.oso.s..s...s.......ooss..sos.',
    badges: '0:6:x,2:8:x,9:15:x,10:11:=,11:17:=,15:16:x,15:21:=,20:26:=,22:23:=,26:27:=,26:32:x,29:35:x,32:33:x,33:34:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 28,
    givens: '......s.........s...so....s.o.o....o',
    badges: '3:4:x,3:9:x,4:10:x,9:10:x,11:17:x,12:13:=,15:16:x,16:22:x,18:24:x,20:21:x,24:25:x,27:33:=,30:31:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 27,
    givens: '...s.......o........o.so...o..o.o.s.',
    badges: '0:1:=,1:2:x,1:7:x,7:8:x,8:14:=,13:14:x,13:19:x,14:15:x,16:17:=,19:20:x,22:23:x,22:28:x,24:25:x,25:31:x,26:32:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 28,
    givens: 'ss........s.o.....s....o.s........s.',
    badges:
        '0:6:x,2:8:x,9:15:x,10:11:=,20:26:=,22:23:=,26:32:x,33:34:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 28,
    givens: 's.o............so........o.o..s..o..',
    badges: '2:8:=,3:9:x,6:12:=,11:17:=,18:24:x,21:22:x,21:27:x,24:25:=,28:29:=,33:34:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 31,
    givens: '...s.......o..........so.o..........',
    badges: '0:1:=,1:2:x,1:7:x,7:8:x,8:14:=,13:14:x,13:19:x,14:15:x,16:17:=,19:20:x,22:28:x,24:25:x,25:31:x,26:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 34,
    givens: '................o...........o.......',
    badges: '5:11:=,9:10:x,13:19:=,17:23:=,20:21:x,21:22:=,22:23:x,25:31:x,27:33:x,32:33:x,34:35:=',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 29,
    givens: '.o.o..........ss.........s.os.......',
    badges:
        '0:1:x,8:14:x,13:14:x,16:22:x,17:23:x,20:21:x,21:27:x,22:23:x,24:25:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 23,
    givens: 's...........o.o..s..o...oo.s..s.osoo',
    badges: '8:9:x,14:20:=,19:25:x,20:21:=,21:22:x,31:32:x,32:33:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 27,
    givens: 'ss..........o............s........so',
    badges: '0:6:x,2:8:x,9:15:x,10:11:=,20:26:=,22:23:=,26:32:x,33:34:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 28,
    givens: '......s...o...o.s.............o....o',
    badges: '3:4:x,3:9:x,4:10:x,9:10:x,11:17:x,12:13:=,15:16:x,16:22:x,18:24:x,20:21:x,24:25:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 28,
    givens: '............o..o.......s............',
    badges: '4:10:x,5:11:=,6:7:x,15:21:x,18:24:x,19:20:=,24:30:=,25:26:x,25:31:x,32:33:x',
  ),
];
