import 'package:puzzle_engine/puzzle_engine.dart';

/// One Duo puzzle whose measured tier is pinned down in source.
class DuoCorpusEntry {
  const DuoCorpusEntry({
    required this.seed,
    required this.difficulty,
    required this.hardest,
    required this.deductions,
    required this.givens,
    required this.badges,
  });

  /// The grid shape. Only the 6x6 today.
  DuoSpec get spec => DuoSpec.standard;

  /// The seed handed to `generateAt`.
  final int seed;

  /// The tier that was asked for, and measured back.
  final PuzzleDifficulty difficulty;

  /// The hardest rung of the ladder the technique solver needed.
  final DuoTechnique hardest;

  /// How many deductions the whole solve took.
  final int deductions;

  /// The givens, one character per cell, row-major: `.` empty, `o` circle,
  /// `s` square.
  final String givens;

  /// The badges, `a:b:r` each with `r` an `=` or an `x`, comma-separated.
  final String badges;

  /// [givens] as the engine wants it.
  List<DuoSymbol?> get givenList => <DuoSymbol?>[
    for (final String cell in givens.split(''))
      switch (cell) {
        'o' => DuoSymbol.circle,
        's' => DuoSymbol.square,
        _ => null,
      },
  ];

  /// [badges] as the engine wants it.
  List<DuoBadge> get badgeList => <DuoBadge>[
    if (badges.isNotEmpty)
      for (final String badge in badges.split(','))
        DuoBadge(
          a: int.parse(badge.split(':')[0]),
          b: int.parse(badge.split(':')[1]),
          relation: badge.split(':')[2] == '='
              ? DuoRelation.equal
              : DuoRelation.unequal,
        ),
  ];
}

/// Duo puzzles with their tiers recorded, so retuning shows up as a diff.
///
/// Difficulty is not an absolute: the boundaries in [DuoBoundaries] and the
/// carving bias in the generator are expected to move as real puzzles
/// accumulate. What must never happen is for them to move *quietly*. Every entry
/// here is regenerated by the same call the app makes, so a change to the
/// ladder, the rater or the generator turns into a visible edit to this file
/// that has to be looked at and accepted, rather than a silent shift in what
/// "Medium" means to a player.
///
/// To regenerate: run the corpus test, read the mismatch it prints, and update
/// the entry — never adjust the assertion to fit.
const List<DuoCorpusEntry> duoDifficultyCorpus = <DuoCorpusEntry>[
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.noTriple,
    deductions: 11,
    givens: 'sso.oo.ososs.os..sss.so..so.s.sosos.',
    badges: '0:6:x,2:8:x,4:10:x,6:7:=,7:8:x,8:9:x,9:15:x,10:11:=,11:17:=,12:13:=,13:14:x,13:19:x,14:15:=,15:16:x,15:21:=,16:17:x,16:22:=,17:23:x,18:19:=,19:20:x,19:25:=,20:21:x,20:26:=,21:22:x,22:23:=,23:29:x,24:25:x,24:30:x,25:26:x,26:27:=,26:32:x,28:29:=,29:35:x,32:33:x,33:34:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.noTriple,
    deductions: 11,
    givens: 'ooso...oo.o..soosoo.soosso.s.o.sos.o',
    badges: '0:6:x,1:2:x,2:8:x,3:4:x,3:9:x,4:10:x,5:11:=,6:7:x,7:8:=,7:13:x,8:14:=,9:10:x,10:11:x,11:17:x,12:13:=,15:16:x,15:21:=,16:17:x,16:22:x,17:23:x,18:24:x,19:20:=,19:25:x,20:21:x,21:22:=,22:23:x,23:29:x,24:25:x,24:30:x,25:26:x,26:32:x,27:33:=,29:35:=,30:31:x,31:32:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.gentle,
    hardest: DuoTechnique.badge,
    deductions: 11,
    givens: 's.os.os..soooo.os.osossos.s.oso...ss',
    badges: '0:1:=,1:2:x,1:7:x,2:8:x,3:4:x,3:9:=,4:5:=,5:11:=,7:8:x,7:13:=,8:14:=,9:10:x,10:16:x,11:17:x,13:14:x,13:19:x,14:15:x,14:20:x,15:16:x,16:17:=,17:23:x,18:24:x,19:20:x,20:21:x,20:26:x,21:22:=,22:23:x,22:28:x,23:29:x,24:25:x,24:30:x,25:26:x,25:31:x,26:27:x,26:32:x,27:33:=,29:35:=,30:31:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 35,
    givens: '..................................s.',
    badges: '0:6:x,2:8:x,6:7:=,8:9:x,9:15:x,10:11:=,11:17:=,12:13:=,13:14:x,13:19:x,14:15:=,15:16:x,15:21:=,16:22:=,17:23:x,18:19:=,19:20:x,19:25:=,20:21:x,20:26:=,21:22:x,22:23:=,23:29:x,24:30:x,26:27:=,26:32:x,29:35:x,32:33:x,33:34:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 32,
    givens: '...o..................o........s.s..',
    badges: '0:6:x,1:2:x,2:8:x,3:4:x,3:9:x,4:10:x,5:11:=,6:7:x,7:13:x,8:14:=,9:10:x,10:11:x,11:17:x,12:13:=,15:16:x,15:21:=,16:17:x,16:22:x,17:23:x,18:24:x,19:20:=,20:21:x,22:23:x,23:29:x,24:25:x,27:33:=,30:31:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.easy,
    hardest: DuoTechnique.lineFull,
    deductions: 35,
    givens: '....................o...............',
    badges: '0:1:=,1:2:x,1:7:x,3:9:=,5:11:=,7:8:x,8:14:=,10:16:x,11:17:x,13:14:x,13:19:x,14:15:x,14:20:x,15:16:x,16:17:=,19:20:x,20:21:x,22:23:x,22:28:x,23:29:x,24:25:x,24:30:x,25:31:x,26:27:x,26:32:x,27:33:=,29:35:=,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 33,
    givens: 'o.................s..s..............',
    badges: '5:11:x,9:15:x,11:17:=,12:18:=,14:20:=,16:22:=,18:24:x,22:23:x,23:29:=,24:25:=,24:30:x,26:32:x,30:31:=,31:32:x,32:33:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 31,
    givens: '........os..........so...........o..',
    badges: '1:2:x,2:3:x,3:4:x,5:11:=,6:7:=,6:12:x,7:8:x,7:13:x,9:10:x,12:13:=,14:20:=,18:19:=,21:22:x,23:29:x,24:25:=,24:30:x,26:27:x,27:33:x,28:29:=,30:31:=,33:34:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.medium,
    hardest: DuoTechnique.sandwich,
    deductions: 32,
    givens: '..o.................o.....so........',
    badges: '0:1:=,1:2:x,1:7:x,3:9:=,7:8:x,8:14:=,10:16:x,11:17:x,13:14:x,13:19:x,14:15:x,14:20:x,15:16:x,16:17:=,19:20:x,22:23:x,22:28:x,23:29:x,24:25:x,25:31:x,26:32:x,29:35:=,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 31,
    givens: 's......os............o........s.....',
    badges:
        '0:1:x,8:14:x,15:21:=,16:17:x,21:27:x,24:30:x,26:27:x,31:32:x,34:35:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 31,
    givens: '..o....s..........o........o..o.....',
    badges: '2:3:x,3:9:=,12:13:=,16:22:x,20:21:x,26:27:x,31:32:x,32:33:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.hard,
    hardest: DuoTechnique.sandwich,
    deductions: 26,
    givens: '..........os..s..o.oo.o.....s...s..o',
    badges: '0:6:=,1:2:x,3:4:x,7:13:x,10:11:x,15:21:x,26:27:x,30:31:x,31:32:x,34:35:=',
  ),
  DuoCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 27,
    givens: 'ss..........o............s........so',
    badges: '0:6:x,2:8:x,9:15:x,10:11:=,20:26:=,22:23:=,26:32:x,33:34:x',
  ),
  DuoCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 28,
    givens: '......s...o...o.s.............o....o',
    badges: '3:4:x,3:9:x,4:10:x,9:10:x,11:17:x,12:13:=,15:16:x,16:22:x,18:24:x,20:21:x,24:25:x,31:32:x',
  ),
  DuoCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: DuoTechnique.lineReading,
    deductions: 28,
    givens: '............o..o.......s............',
    badges: '4:10:x,5:11:=,6:7:x,15:21:x,18:24:x,19:20:=,24:30:=,25:26:x,25:31:x,32:33:x',
  ),
];
