import 'package:puzzle_engine/puzzle_engine.dart';

/// One puzzle whose measured tier is pinned down in source.
class CorpusEntry {
  const CorpusEntry({
    required this.spec,
    required this.seed,
    required this.difficulty,
    required this.hardest,
    required this.deductions,
    required this.givens,
  });

  /// The grid shape it was generated for.
  final SudokuSpec spec;

  /// The seed handed to `generateAt`.
  final int seed;

  /// The tier that was asked for, and measured back.
  final SudokuDifficulty difficulty;

  /// The hardest rung of the ladder the technique solver needed.
  final SudokuTechnique hardest;

  /// How many deductions the whole solve took.
  final int deductions;

  /// The starting grid, one character per cell, `0` for empty.
  final String givens;

  /// [givens] as the engine wants it.
  List<int> get cells =>
      givens.split('').map((String digit) => int.parse(digit)).toList();
}

/// Puzzles with their tiers recorded, so retuning shows up as a diff.
///
/// Difficulty is not an absolute: the tier boundaries in `DifficultyBoundaries`
/// are expected to move as real puzzles accumulate. What must never happen is
/// for them to move *quietly*. Every entry here is regenerated by the same call
/// the app makes, so a change to the ladder, the rater or the generator turns
/// into a visible edit to this file that has to be looked at and accepted,
/// rather than a silent shift in what "Medium" means to a player.
///
/// To regenerate: run the corpus test, read the mismatch it prints, and update
/// the entry — never adjust the assertion to fit.
const List<CorpusEntry> difficultyCorpus = <CorpusEntry>[
  CorpusEntry(
    spec: SudokuSpec.mini,
    seed: 101,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 12,
    givens: '0000040000020301',
  ),
  CorpusEntry(
    spec: SudokuSpec.mini,
    seed: 102,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 12,
    givens: '0030000004003010',
  ),
  CorpusEntry(
    spec: SudokuSpec.mini,
    seed: 103,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 12,
    givens: '0002030000030400',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 101,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 27,
    givens: '500600000201062000000000630000000400',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 102,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 23,
    givens: '500640020510300020060400400000000204',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 103,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 24,
    givens: '500000340560030140000000025601000000',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 101,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 26,
    givens: '000104040300054000003000200030000500',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 102,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 27,
    givens: '500640020500300000060000400000000200',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 103,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 26,
    givens: '500000300060030140000000025601000000',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 101,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.simpleColouring,
    deductions: 28,
    givens: '000004640000000500061000000020020106',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 102,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.simpleColouring,
    deductions: 31,
    givens: '020000500060000030000005300050050400',
  ),
  CorpusEntry(
    spec: SudokuSpec.light,
    seed: 103,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.xyWing,
    deductions: 30,
    givens: '200050000000000006001400400201030000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 101,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 53,
    givens: '000500000006000370047102006200010000401920000000005920000000084000009560520460007',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 102,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 49,
    givens: '608500403000260050050008200017903065000607100400010300090402501000090000080006004',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 103,
    difficulty: SudokuDifficulty.gentle,
    hardest: SudokuTechnique.nakedSingle,
    deductions: 49,
    givens: '080300005000004370007009180014950000003060010002010804008040200290001507500207000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 101,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 55,
    givens: '000500000006000370047100006200010000401920000000005920000000084000000560520460007',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 102,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 56,
    givens: '008500400000260000050008200017003065000007000400010300090400501000090000080006004',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 103,
    difficulty: SudokuDifficulty.easy,
    hardest: SudokuTechnique.hiddenSingle,
    deductions: 55,
    givens: '080000005000004370007009180004950000003060010000010804008040200290000507500000000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 101,
    difficulty: SudokuDifficulty.medium,
    hardest: SudokuTechnique.nakedPair,
    deductions: 59,
    givens: '000500000006000370047100006200000000401920000000005900000000084000000060520460007',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 102,
    difficulty: SudokuDifficulty.medium,
    hardest: SudokuTechnique.nakedPair,
    deductions: 60,
    givens: '020000400080001000000389100070000080000605340400000060004000900000800010590200000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 103,
    difficulty: SudokuDifficulty.medium,
    hardest: SudokuTechnique.pointingPair,
    deductions: 60,
    givens: '000400790100200000900000016040390000060000470010005000002630080800000000000071000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 101,
    difficulty: SudokuDifficulty.hard,
    hardest: SudokuTechnique.nakedPair,
    deductions: 61,
    givens: '280000060009000030140000800001056000000201000000000700900063000000048320060005040',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 102,
    difficulty: SudokuDifficulty.hard,
    hardest: SudokuTechnique.nakedPair,
    deductions: 60,
    givens: '000030610000000000008000920800900001060200000450000360000008005302607000010009070',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 103,
    difficulty: SudokuDifficulty.hard,
    hardest: SudokuTechnique.boxLineReduction,
    deductions: 61,
    givens: '000000000048073001200600400000040083080000000705906000620000000070300000000008904',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 101,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.xyWing,
    deductions: 56,
    givens: '008000003001064008000020400900005084803000020600270090000906800000003640009400030',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 102,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.xyWing,
    deductions: 57,
    givens: '014070300920106800030000509000000050400001900790000281009600004000900700100200000',
  ),
  CorpusEntry(
    spec: SudokuSpec.classic,
    seed: 103,
    difficulty: SudokuDifficulty.fiendish,
    hardest: SudokuTechnique.xyWing,
    deductions: 57,
    givens: '500020004002000580048510000010690030604800070000050002000900000069070800450186000',
  ),
];
