import 'package:puzzle_engine/puzzle_engine.dart';

/// One Stars puzzle whose measured tier is pinned down in source.
class StarsCorpusEntry {
  const StarsCorpusEntry({
    required this.seed,
    required this.difficulty,
    required this.hardest,
    required this.deductions,
    required this.regions,
  });

  /// The grid shape. Only the 8x8 today.
  StarsSpec get spec => StarsSpec.standard;

  /// The seed handed to `generateAt`.
  final int seed;

  /// The tier that was asked for, and measured back.
  final PuzzleDifficulty difficulty;

  /// The hardest rung of the ladder the technique solver needed.
  final StarsTechnique hardest;

  /// How many deductions the whole solve took.
  final int deductions;

  /// The region of each cell, one digit per cell, row-major.
  final String regions;

  /// [regions] as the engine wants it.
  List<int> get regionList =>
      regions.split('').map((String digit) => int.parse(digit)).toList();
}

/// Stars puzzles with their tiers recorded, so retuning shows up as a diff.
///
/// Difficulty is not an absolute: the boundaries in [StarsBoundaries] and the
/// growth bias in the generator are expected to move as real puzzles
/// accumulate. What must never happen is for them to move *quietly*. Every
/// entry here is regenerated by the same call the app makes, so a change to the
/// ladder, the rater or the generator turns into a visible edit to this file
/// that has to be looked at and accepted, rather than a silent shift in what
/// "Medium" means to a player.
///
/// To regenerate: run the corpus test, read the mismatch it prints, and update
/// the entry — never adjust the assertion to fit.
const List<StarsCorpusEntry> starsDifficultyCorpus = <StarsCorpusEntry>[
  StarsCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.gentle,
    hardest: StarsTechnique.regionSingle,
    deductions: 8,
    regions: '1112002211122222111122224513322245553222555552225555622255552227',
  ),
  StarsCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.gentle,
    hardest: StarsTechnique.regionSingle,
    deductions: 8,
    regions: '2011111122111111222111114611131146611715666677756666777777777777',
  ),
  StarsCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.gentle,
    hardest: StarsTechnique.regionSingle,
    deductions: 8,
    regions: '0111111122111111221111115553111155551141555511615555666655555766',
  ),
  StarsCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.easy,
    hardest: StarsTechnique.lineSingle,
    deductions: 8,
    regions: '1111111011111214111112241113224411111644551166645516666675166666',
  ),
  StarsCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.easy,
    hardest: StarsTechnique.lineSingle,
    deductions: 8,
    regions: '1133332013333222333332223333332233337477666574776667777766777777',
  ),
  StarsCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.easy,
    hardest: StarsTechnique.lineSingle,
    deductions: 8,
    regions: '0221114422211444222444442223444422444444255444442554466625547766',
  ),
  StarsCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.medium,
    hardest: StarsTechnique.regionConfinedToLine,
    deductions: 9,
    regions: '0003333300333331203333335556463355564666556666665555666655576666',
  ),
  StarsCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.medium,
    hardest: StarsTechnique.regionConfinedToLine,
    deductions: 10,
    regions: '2111133022211333422223354444435544444555444445554466445544667755',
  ),
  StarsCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.medium,
    hardest: StarsTechnique.regionConfinedToLine,
    deductions: 9,
    regions: '0333111122331111223331115333314453333144555333335553336655553766',
  ),
  StarsCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.hard,
    hardest: StarsTechnique.regionConfinedToLine,
    deductions: 11,
    regions: '1333022213333222173352227773552277555544775555547775556477755564',
  ),
  StarsCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.hard,
    hardest: StarsTechnique.lineConfinedToRegion,
    deductions: 12,
    regions: '0023333322223331222233332233333324433333444435336774373367777733',
  ),
  StarsCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.hard,
    hardest: StarsTechnique.regionConfinedToLine,
    deductions: 11,
    regions: '0222222122222221444222214422223144226221465562216666666667766666',
  ),
  StarsCorpusEntry(
    seed: 1,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: StarsTechnique.regionSetCover,
    deductions: 11,
    regions: '0000000210000002100000221003307214037772443357764333777633337766',
  ),
  StarsCorpusEntry(
    seed: 2,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: StarsTechnique.regionSetCover,
    deductions: 12,
    regions: '0022111122221111222111112221131142111115621111156666111566677775',
  ),
  StarsCorpusEntry(
    seed: 3,
    difficulty: PuzzleDifficulty.fiendish,
    hardest: StarsTechnique.regionSetCover,
    deductions: 9,
    regions: '0003111103333111033323310333333333333433636534446666774466777744',
  ),
];
